function init(self)
	print("Here is how you normally create new generator state:")
	local state_52bit = xoshiro256.seed(os.time())

	print("However lua numbers are stored as doubles and cannot represent full 64 bits of precision, so you can use decimal string instead:")
	local state_64bit = xoshiro256.seed('01234567890123456789')

	print("Here is how you generate numbers. API mirrors the behavior of math.random()")
	local num1 = xoshiro256.random(state_64bit)
	local num2 = xoshiro256.random(state_64bit, 100)
	local num3 = xoshiro256.random(state_64bit, 5, 42)

	print("Number in range [0, 1): " .. num1)
	print("Number in range [1, 100]: " .. num2)
	print("Number in range [5, 42]: " .. num3)

	print("If you need fully deterministic system you can save and restore generator state:")
	local saved_state = xoshiro256.to_string(state_64bit)
	print("This produces string of four colon-separated decimal values: " .. saved_state)

	print("So you can save this string however you want and restore it later:")
	local restored_state = xoshiro256.from_string(saved_state)

	print("If you need to clone generator state before continuing sequence (for tests, perhaps?), you can do it like this:")
	local cloned_state = xoshiro256.clone(state_64bit)

	print("Here is the proof that cloned and restored generators produce the exact same sequence:")
	for _ = 1, 100 do
		local original_num = xoshiro256.random(state_64bit)
		local restored_num = xoshiro256.random(restored_state)
		local cloned_num = xoshiro256.random(cloned_state)
		assert(original_num == restored_num and original_num == cloned_num, "Generator state mismatch!")
	end

	print("You also can print generator state for debugging purposes, like this: " .. tostring(state_64bit))
end
